# Generated by Django 4.2.1 on 2023-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='fa', max_length=6, null=True, verbose_name='زبان'),
        ),
    ]
