# Generated by Django 4.2.1 on 2023-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='HGJHFjdfgh@UIF%^$#*&^%AAAAAA', max_length=150, verbose_name='شاه کلید')),
            ],
            options={
                'verbose_name': 'شاه کلید',
                'verbose_name_plural': 'شاه کلید',
            },
        ),
    ]
