# Generated by Django 4.2.1 on 2023-05-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hotkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotKey',
        ),
    ]
