# Generated by Django 4.2.1 on 2023-05-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_representative_traffic_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={'verbose_name': 'تعیین نماینده', 'verbose_name_plural': 'تعیین نمایندگان'},
        ),
    ]
