# Generated by Django 4.2.1 on 2023-05-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_representative_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ایمیل'),
        ),
    ]
