# Generated by Django 4.2.2 on 2023-06-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_representative_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام کسب و کار')),
                ('activity_type', models.CharField(max_length=150, verbose_name='نوع فعالیت')),
                ('domain', models.CharField(max_length=150, verbose_name='دامنه')),
                ('start_work', models.CharField(max_length=150, verbose_name='شروع کاری')),
                ('end_work', models.CharField(max_length=150, verbose_name='پایان کاری')),
                ('days_work', models.CharField(max_length=500, verbose_name='روز های کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
            options={
                'verbose_name': 'کسب و کار',
                'verbose_name_plural': 'کسب و کار ها',
            },
        ),
        migrations.DeleteModel(
            name='BlockUserIP',
        ),
        migrations.RemoveField(
            model_name='language',
            name='country',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='servers',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='users',
        ),
        migrations.RemoveField(
            model_name='server',
            name='country',
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='decrypted_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_representative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='representation',
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دامنه ثبت نامی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AddField(
            model_name='useractivityinformations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
