# Generated by Django 4.2.2 on 2023-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useractivityinformations_delete_blockuserip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ایمیل'),
        ),
    ]
