# Generated by Django 4.2.2 on 2023-07-05 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_user',
            field=models.BooleanField(default=True, verbose_name='کاربر مستقیم'),
        ),
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
