# Generated by Django 4.2.2 on 2023-07-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_domain_user_customer_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
