# Generated by Django 4.2.2 on 2023-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_address_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='وضعیت'),
        ),
    ]
