# Generated by Django 4.2.2 on 2023-07-11 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
